// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNeG4ZCBNoNh3FfWqgHGgAqEToCIkZse8',
    appId: '1:702964672530:web:124c8eeef4b99d2527d0cb',
    messagingSenderId: '702964672530',
    projectId: 'smash-2159f',
    authDomain: 'smash-2159f.firebaseapp.com',
    storageBucket: 'smash-2159f.firebasestorage.app',
    measurementId: 'G-MV623BLK56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDos6U6GFG05jTUHxtPlrzWOl7oVY27TqI',
    appId: '1:702964672530:android:832036c625864ba227d0cb',
    messagingSenderId: '702964672530',
    projectId: 'smash-2159f',
    storageBucket: 'smash-2159f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySuCpBOSl-9xjnLqTR7trhp-WkxEDm7o',
    appId: '1:702964672530:ios:721a43203dca583927d0cb',
    messagingSenderId: '702964672530',
    projectId: 'smash-2159f',
    storageBucket: 'smash-2159f.firebasestorage.app',
    iosBundleId: 'com.example.smash',
  );
}
